MuchoMasFacil\InlineEditableContentsBundle\Entity\Content:
    type: entity
    repositoryClass: MuchoMasFacil\InlineEditableContentsBundle\Entity\ContentRepository
    table: null
    id:
        handler:
            type: string
            length: 255
            id: true
            generator:
                strategy: NONE
    fields:
        yml_params: {type: text}
        yml_editor_roles: {type: text}
        yml_admin_roles: {type: text}
        entity_class: {type: string, length: 255}
        form_class: {type: string, length: 255}
        render_template: {type: string, length: 255}
        form_template: {type: string, length: 255}
        collection_length: {type: integer, nullable: true}
        content: {type: array, nullable: true}
    lifecycleCallbacks: {}
        #prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]

