parameters:
#    mucho_mas_facil_inline_editable_contents.example.class: MuchoMasFacil\InlineEditableContentsBundle\Example

services:
#    mucho_mas_facil_inline_editable_contents.example:
#        class: %mucho_mas_facil_inline_editable_contents.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
