parameters:
    mucho_mas_facil_inline_editable_contents.widgets:
        default:
            yml_params: '{}'
            yml_editor_roles: '[ROLE_USER]'
            yml_admin_roles: '[ROLE_ADMIN]'
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\PlainText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\PlainTextType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/PlainText.html.twig'
            form_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Includes/form_template.html.twig'

        plain_text: ~ #same as default

        multi_line_plain_text:
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\MultiLinePlainText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\MultiLinePlainTextType

        rich_text:
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\RichText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\RichTextType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/RichText.html.twig'

        custom_rich_text:
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\CustomRichText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\RichTextType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/RichText.html.twig'
            yml_params: |
                ckeditor_load_option: custom
                ckeditor_custom_options: |
                    //esta es una opción
        plain_text_header_and_custom_rich_text:
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\PlainTextHeaderAndCustomRichText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\PlainTextHeaderAndCustomRichTextType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/PlainTextHeaderAndCustomRichText.html.twig'

        rich_text_header_and_custom_rich_text:
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\RichTextHeaderAndCustomRichText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\RichTextHeaderAndCustomRichTextType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/RichTextHeaderAndCustomRichText.html.twig'

        advanced_image:  #image_url, posible title or text, posible link
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\AdvancedImage
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\AdvancedImageType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/AdvancedImage.html.twig'
            yml_params: |
                mmf_fm_load_options: single_image

        image:  #image_url, posible title or text, posible link
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\Image
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\ImageType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/Image.html.twig'
            yml_params: |
                mmf_fm_load_options: collection_image

        raw: #use with care may end with js malscripting
            entity_class: MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\MultilinePlainText
            form_class: MuchoMasFacil\InlineEditableContentsBundle\Form\Content\MultilinePlainTextType
            render_template: 'MuchoMasFacilInlineEditableContentsBundle:Content:Render/RichText.html.twig'


        #advanced_image: ~ #this are just calls to FileManagerBundle

    mucho_mas_facil_inline_editable_contents.ckeditor_options:
        default: |
            config.toolbar = 'Default';
            config.toolbar_Default =
            [
                ['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink','-','About']
            ];


        full: |
            config.toolbar = 'Full';


        basic: |
            config.toolbar = 'Basic';


        custom: |
            config.toolbar = 'Custom';
            config.toolbar_Custom =
            [
                { name: 'document', items : [ 'Source','-','Templates' ] },
                { name: 'clipboard', items : [ 'Cut','Copy','PasteText','-','Undo','Redo' ] },
                { name: 'editing', items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] },
                { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                '/',
                { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-'
                 ,'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
                 '/',
                { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar' ] },
                { name: 'styles', items : [ 'Format' ] },
                { name: 'tools', items : [ 'Maximize', 'ShowBlocks','-','About' ] }
            ];

services:
#    mucho_mas_facil_inline_editable_contents.example:
#        class: %mucho_mas_facil_inline_editable_contents.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

