parameters:
    mucho_mas_facil_inline_editable_contents.ckeditor_options:
        default: |

            config.toolbar = 'Default';
            config.toolbar_Default =
            [
                ['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink','-','About']
            ];
        full: |

            config.toolbar = 'Full';
        basic: |

            config.toolbar = 'Basic';
        custom: |

            config.toolbar = 'Custom';
            config.toolbar_Custom =
            [
                { name: 'document', items : [ 'Source','-','Templates' ] },
                { name: 'clipboard', items : [ 'Cut','Copy','PasteText','-','Undo','Redo' ] },
                { name: 'editing', items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] },
                { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                '/',
                { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-'
                 ,'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
                 '/',
                { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar' ] },
                { name: 'styles', items : [ 'Format' ] },
                { name: 'tools', items : [ 'Maximize', 'ShowBlocks','-','About' ] }
            ];

services:
#    mucho_mas_facil_inline_editable_contents.example:
#        class: %mucho_mas_facil_inline_editable_contents.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

