MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\PlainText:
    properties:
        content:
            - NotBlank: ~

MuchoMasFacil\InlineEditableContentsBundle\Entity\Content\RichText:
    properties:
        content:
            - NotBlank: ~

MuchoMasFacil\InlineEditableContentsBundle\Entity\Content:
    properties:
        #yml_params:
            #Yml: ~
        #yml_editor_roles:
            #Yml: ~
        #yml_admin_roles:
            #Yml: ~
        entity_class:
            - NotBlank: ~
        form_class:
            - NotBlank: ~
        collection_length:
            - Min:
                limit: 1
        render_template:
            - NotBlank: ~

